# Generated by Django 3.2.8 on 2021-11-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('content', models.IntegerField()),
                ('codename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBasic',
            fields=[
                ('student_name', models.AutoField(primary_key=True, serialize=False)),
                ('student_email', models.CharField(max_length=255)),
                ('student_password', models.CharField(max_length=255)),
                ('is_superuser', models.IntegerField()),
            ],
            options={
                'db_table': 'student_basic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeacherBasic',
            fields=[
                ('teacher_name', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_email', models.CharField(max_length=255)),
                ('teacher_password', models.CharField(max_length=255)),
                ('is_superuser', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher_basic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserStudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='APIs.studentbasic')),
                ('user_biography', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_telephone', models.IntegerField()),
            ],
            options={
                'db_table': 'user_student_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTeacherProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='APIs.teacherbasic')),
                ('user_subject_type', models.IntegerField()),
                ('user_biography', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('user_telephone', models.IntegerField()),
            ],
            options={
                'db_table': 'user_teacher_profile',
                'managed': True,
                'unique_together': {('user', 'user_subject_type')},
            },
        ),
        migrations.CreateModel(
            name='CourseBasic',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('course_amount', models.IntegerField()),
                ('course_payment_currecy', models.DateTimeField()),
                ('course_status', models.IntegerField()),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APIs.teacherbasic')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APIs.studentbasic')),
            ],
            options={
                'db_table': 'course_basic',
                'managed': True,
                'unique_together': {('transaction_id', 'student')},
            },
        ),
    ]
