# Generated by Django 3.2.8 on 2021-11-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbasic',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacherbasic',
            name='is_superuser',
            field=models.IntegerField(default=0),
        ),
    ]
