# Generated by Django 3.2.8 on 2021-11-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_auto_20211121_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudentprofile',
            name='user_firstname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userstudentprofile',
            name='user_secondname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userteacherprofile',
            name='user_firstname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='userteacherprofile',
            name='user_secondname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
