# Generated by Django 3.2.8 on 2021-11-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_auto_20211121_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBasic',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subject_basic',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='userteacherprofile',
            name='user_subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='APIs.subjectbasic'),
        ),
    ]
